// This file is auto-generated by @hey-api/openapi-ts

export { type Options, processImageImagePost, processPdfPdfPost } from './sdk.gen.js';
export type { BaseRequest, BoundingBox, CellContent, ClientOptions, HttpValidationError, PdfRequest, PdfTableResponse, ProcessImageImagePostData, ProcessImageImagePostError, ProcessImageImagePostErrors, ProcessImageImagePostResponse, ProcessImageImagePostResponses, ProcessPdfPdfPostData, ProcessPdfPdfPostError, ProcessPdfPdfPostErrors, ProcessPdfPdfPostResponse, ProcessPdfPdfPostResponses, TableResponse, ValidationError } from './types.gen.js';
