// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { ProcessImageImagePostData, ProcessImageImagePostErrors, ProcessImageImagePostResponses, ProcessPdfPdfPostData, ProcessPdfPdfPostErrors, ProcessPdfPdfPostResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Process Image
 */
export const processImageImagePost = <ThrowOnError extends boolean = false>(options: Options<ProcessImageImagePostData, ThrowOnError>) => (options.client ?? client).post<ProcessImageImagePostResponses, ProcessImageImagePostErrors, ThrowOnError>({
    url: '/image',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Process Pdf
 */
export const processPdfPdfPost = <ThrowOnError extends boolean = false>(options: Options<ProcessPdfPdfPostData, ThrowOnError>) => (options.client ?? client).post<ProcessPdfPdfPostResponses, ProcessPdfPdfPostErrors, ThrowOnError>({
    url: '/pdf',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
